language: r
r: bioc-devel
cache: packages
sudo: true
dist: trusty

apt_packages:
  - libnetcdf-dev
  - netcdf-bin # libnetcdf-dev doesn't contain nc-config in ubuntu 12.04 (in 16.04 it is part of libnetcdf-dev)

r_packages:
  - devtools
  - covr

script:
  - |
    travis_wait 40 R CMD build .

bioc_packages:
  - MSnbase
  - pRoloc
